### with correct body
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Nueva nota v2 with false"
}

### without correct body

POST http://localhost:3001/api/notes 
Content-Type: application/json
